weatherapi.key=0f61dee0820846289d1141927260707
weatherapi.base-url=http://api.weatherapi.com/v1
weatherapi.location=Buenos Aires

alert.mails[0]=admin@clima.com
alert.mails[1]=emergencias@clima.com
alert.mails[2]=meteorologia@clima.com

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=tu_email@gmail.com
spring.mail.password=tu_password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true