weatherapi.key=0f61dee0820846289d1141927260707
weatherapi.base-url=http://api.weatherapi.com/v1
weatherapi.location=Buenos Aires

alert.mail[0]=admin@clima.com
alert.mail[1]=emergencias@clima.com
alert.mail[2]=meteorologia@clima.com